config/routes.rb
Rails.application.routes.draw do

  root 'static#welcome'
  
  resources :products do
    resources :reviews, except: [:new]
    member do
      put "like", to: "products#upvote"
      put "dislike", to: "products#downvote"
    end
  end 

  
  
  


  resources :users, except: [:new, :create]
   
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/auth/amazon/callback' => 'sessions#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end

app/views/layouts/nav/_dropdown.html.erb
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      My Account
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
      <%= link_to "my reviews", user_path(current_user), class: "dropdown-item" %>
      <a class="dropdown-item" href="#">Another action</a>
      <%= link_to "Logout", logout_path, class: "dropdown-item", method: "delete" %>
    </div>
  </li>

app/views/layouts/nav/_navbar.html.erb
<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
  <%= link_to "Product Review", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <ul class="navbar-nav">
    <li class="nav-item">
        <%= link_to "User Rankings", users_path, class: "nav-link" %>
    </li>
  </ul>
  <div class="collapse navbar-collapse" id="navbarNav">
    <%= product_dropdown %>
    <ul class="navbar-nav ml-auto">
      <%= nav_content %>
    </ul>
  </div>
</nav>

app/views/layouts/nav/_product_dropdown.html.erb
<ul class="navbar-nav">

  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Products
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
      <%= link_to "All Products", products_path, class: "dropdown-item" %>
      <%= link_to "Add Product", new_product_path, class: "dropdown-item" %>
    </div>
  </li>
</ul>

app/views/layouts/nav/_user_dropdown.html.erb
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      My Account
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
      <%= link_to "My Page", user_path(current_user), class: "dropdown-item" %>
      <%= link_to "Edit my info", edit_user_path(current_user), class: "dropdown-item" %>
      <%= link_to "Logout", logout_path, class: "dropdown-item", method: "delete" %>
    </div>
  </li>