config/routes.rb
Rails.application.routes.draw do

  root 'static#welcome'
  
  resources :products do
    resources :reviews, except: [:new]
    member do
      put "like", to: "products#upvote"
      put "dislike", to: "products#downvote"
    end
  end 

  
  
  


  resources :users, except: [:new, :create]
   
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/auth/amazon/callback' => 'sessions#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :top_user


  def current_user
      @user ||= User.find_by(id: session[:user_id]) if session[:user_id].present?
  end
  
  def logged_in?
    !!current_user
  end

  def require_logged_in
   redirect_to(controller: 'sessions', action: 'new') unless logged_in?
  end

  def top_user
    User.most_reviews
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_content
    if logged_in?
      user_dropdown_nav
    else
      amazon_img_login_link + login_nav_link + signup_nav_link
    end
  end
  
  def login_nav_link
    content_tag(:li, link_to("Login", login_path, class: "nav-link"), class: "nav-item")
  end

  def signup_nav_link
    content_tag(:li, link_to("Signup", signup_path, class: "nav-link"), class: "nav-item")
  end

  def user_dropdown_nav
    render  "layouts/nav/user_dropdown" if logged_in?
  end 

  def product_dropdown
    render "layouts/nav/product_dropdown" if logged_in?
  end

  def amazon_img_login_link
    link_to('/auth/amazon') do
      image_tag("https://images-na.ssl-images-amazon.com/images/G/01/lwa/btnLWA_gold_156x32.png", alt: "Login with Amazon", class: "nav-link")
    end 
  end

  def flash_message(flash, color)
    if flash
      content_tag :div, flash, 'role' => "alert", class: "alert alert-#{color}"
    end
  end

  def page_header(header_text, sub_header: nil)
    content_tag :div, class: "card-body  bg-light text-center border-bottom" do
    content_tag(:h1, header_text, class: "display-4") +
    content_tag(:p, sub_header, class: "h4 text-muted")
    end
  end

end

app/views/application/_card_reviews.html.erb
<%= div_card_for_review(review) do %>
  <div class="card-body">
    <h6 class="card-subtitle mb-2 text-muted justify-content-between d-flex">reviewed by:
      <%= delete_comment(review) %>
    </h6>
    <h5 class="card-title justify-content-between d-flex"><%= review.users_name %></h5>
    <p class="card-text"><%= review.content %></p>
    <%= link_to "Product Page", product_reviews_path(review.product), class: "productPageLink card-link" unless current_page?(action: 'index') %>
    <%= review_edit_link(review) %>
  </div>
<% end %>

app/views/application/_modal_description.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-sm btn-primary" data-toggle="modal" data-target="#<%= product.description %>">
    Description
  </button>
  
  <!-- Modal -->
  <div class="modal fade" id="<%= product.description %>" tabindex="-1" role="dialog" aria-labelledby="description" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="description">Description</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= product.description %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

app/views/application/_modal_reviews.html.erb
  
<button type="button" class="btn btn-sm btn-primary" data-toggle="modal" data-target="#<%= product.name %>">
    Reviews
  </button>
  <div class="modal fade" id="<%= product.name %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Reviews</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <%= render collection: product.reviews, partial: "card_reviews", as: :review %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

app/views/application/_shared_errors.html.erb
<% if obj.errors.any? %>
  <ul class="list-group">
    <% obj.errors.each do |attribute, message| %>
      <small class="form-text text-danger"><%= "#{attribute unless attribute == :user_id} #{message}" %></small>
      
    <% end %>
  </ul>
<% end %>

app/views/application/_vote_buttons.html.erb
<div class="btn-group-vertical mx-auto" id="votes">
    <%= link_to like_product_path(@product), method: :put, id: "upVote", class: "btn btn-success mb-1" do %> 
    Upvote
    <span class="badge badge-light" id="upVoteCount"><%= @product.get_upvotes.size %></span>
    <span class="sr-only">Upvotes</span>
    <% end %>
    <%= link_to dislike_product_path(@product), method: :put, id: "downVote", class: "btn btn-success" do %> 
    Downvote
    <span class="badge badge-light" id="downVoteCount"><%= @product.get_downvotes.size %></span>
    <span class="sr-only">Downvotes</span>
    <% end %>
  </div>